export const HTTP_ERROR_SUFFIX = '失败';
export const HTTP_SUCCESS_SUFFIX = '成功';

export const HTTP_DEFAULT = '数据请求';
export const HTTP_DEFAULT_ERROR = HTTP_DEFAULT + HTTP_ERROR_SUFFIX;
export const HTTP_DEFAULT_SUCCESS = HTTP_DEFAULT + HTTP_SUCCESS_SUFFIX;

export const HTTP_UNAUTHORIZED = '权限验证';
export const HTTP_UNAUTHORIZED_ERROR = HTTP_UNAUTHORIZED + HTTP_ERROR_SUFFIX;
export const HTTP_UNAUTHORIZED_SUCCESS = HTTP_UNAUTHORIZED + HTTP_SUCCESS_SUFFIX;

export const HTTP_BAD_REQUEST = '未知错误';
export const HTTP_FORBIDDEN = '无权访问';

export const HTTP_VALIDATION = '参数验证';
export const HTTP_VALIDATION_ERROR = HTTP_VALIDATION + HTTP_ERROR_SUFFIX;
export const HTTP_VALIDATION_SUCCESS = HTTP_VALIDATION + HTTP_SUCCESS_SUFFIX;
