export const labsData = [{
  name: 'Parser',
  desc: '这是一个静态页面爬虫解析器。',
  url: 'https://www.npmjs.com/package/almighty-parser-core'
}, {
  name: 'ANIMATE.CSS',
  desc: '基于CSS3的运动效果库，通过引入css，修改class即可看到效果。',
  url: 'https://coolfishstudio.github.io/cfs.animate.css'
}, {
  name: 'SNOW.JS',
  desc: '基于canvas绘制的下雪效果的组件，通过引入js，一句js即可实现下雪效果。',
  url: 'https://coolfishstudio.github.io/cfs.snow.js'
}, {
  name: '小球称重',
  desc: '基于js实现找出用天秤找出异常小球，并指出它是偏轻还是偏重的游戏案例。',
  url: 'https://coolfishstudio.github.io/game-ball-weighing'
}, {
  name: '捕鱼达人',
  desc: '基于canvas的做的仿制捕鱼达人小游戏DEMO。',
  url: 'http://coolfishstudio.github.io/game-fishing-single'
}, {
  name: '卡通飞行',
  desc: '使用Egret游戏引擎做的一个打飞机游戏，这是我学习egret所写的第一个小游戏。',
  url: 'http://flight.coolfishstudio.com',
  hide: true
}, {
  name: '微信摇一摇',
  desc: '基于HTML5的运动传感器，模拟摇一摇被触发才执行的事件效果。',
  url: 'http://coolfishstudio.github.io/game-shake'
}, {
  name: '消灭蓝块',
  desc: '无意间翻出2015年写的一个H5小游戏，请用手机模式，点击蓝块，最后满屏红块即为赢。',
  url: 'https://coolfishstudio.github.io/game-xmlk'
}, {
  name: '井字棋',
  desc: '无意间翻出2015年写的一个H5小游戏，请用手机模式，三子成线即为赢。',
  url: 'https://coolfishstudio.github.io/game-jzq'
}, {
  name: '2048',
  desc: '无意间翻出2015年写的一个H5小游戏，请用手机模式，滑动屏幕，相同数字可组合。',
  url: 'https://coolfishstudio.github.io/game-2048'
}, {
  name: '中国传统色谱',
  desc: '提供各种中国的传统颜色的名称，HEX值，RGB值',
  url: 'https://coolfishstudio.github.io/cfs-color'
}]
